# Generated by Django 3.2.16 on 2024-10-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
