# Generated by Django 3.2.16 on 2024-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
